Algoritmo "Meu primeiro algoritmo"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   :
// Descrição   : Este programa é bem simples. Imprime na tela o resultado de uma nota
// Autor(a)    : Lidiane de Souza Foorte de Oliveira
// Data atual  : 20/10/2020
Var
// Seção de Declarações das variáveis 
   nota: inteiro


Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   nota <- 100
   escreva("resultado:",nota)


Fimalgoritmo