Algoritmo "Variável"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 20/10/2020
Var
// Seção de Declarações das variáveis 
   PrimeiroNome ,SegundoNome, cidade,endereco:caractere,
   idade:inteiro


   


Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 


Fimalgoritmo